apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment-principal
  namespace: k-att-y70-dev
  labels:
    app: mi-app-principal
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-principal
  template:
    metadata:
      labels:
        app: mi-app-principal
    spec:
      containers:
        - name: contenedor-principal
          #image: image-registry.openshift-image-registry.svc:5000/k-att-y70-dev/ejercicioclase-git-app-phyton:build-{{ tag }}
          image: boriscutos/pruebas-seguridad:build-{{ tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap-principal
            - secretRef:
                name: mi-secret-principal
          startupProbe:
            httpGet:
              path: /startup
              port: 3000
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10  
          #volumeMounts:
            #- name: datos
              #mountPath: "/app/data"
      #volumes:
        #- name: datos
          #persistentVolumeClaim:
            #claimName:  mi-pvc-v2
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-principal
  namespace: k-att-y70-dev  # Asegúrate de que coincida con tu Deployment
spec:
  selector:
    app: mi-app-principal  # Debe coincidir con las labels del Deployment
  ports:
    - protocol: TCP
      port: 4000        # Puerto del Service
      targetPort: 3000  # Puerto del contenedor
  type: ClusterIP     # Cambia a NodePort o LoadBalancer si quieres acceso externo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap-principal
  namespace: k-att-y70-dev
data:
  DATABASE: "192.168.1.1"
---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret-principal
  namespace: k-att-y70-dev
type: Opaque
data:
  PASSWORD: aG9sYQ==

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa-principal
  namespace: k-att-y70-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: mi-deployment-principal
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc-principal
  namespace: k-att-y70-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3